# Generated by Django 5.2.14 on 2026-05-12 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='post',
            name='media_type',
            field=models.CharField(choices=[('IMAGE', '이미지'), ('VIDEO', '영상')], default='VIDEO', max_length=10),
        ),
    ]
