# Generated by Django 5.2.14 on 2026-05-12 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_post_image_post_media_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='ascii_width',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
