# Generated by Django 5.2.14 on 2026-05-27 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0003_alter_post_ascii_width"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="ascii_image",
            field=models.FileField(blank=True, null=True, upload_to="ascii_images/"),
        ),
    ]
